### ISSUE TITLE
Compiling the mCRL2 prerequisite fails

### ISSUE THREAD

**Issue by trolando** [jkeiren/paritygame-generator#2]
On Ubuntu, Boost 1.62, compiling mcrl2_data (as part of the prerequisite installation) fails spectacularly with templating errors related to ranges and iterators.

**Comment by jkeiren** [comment]
Attached is a patch that fixes compilation with the mentioned revisions on Ubuntu 17.04. This patch mainly addressed some interface changes in recent Boost versions.

However, it appears there are some issues with the used mCRL2 revision when compiling using recent clang++ versions, so the tools build, but segfault deep down in the atermpp library when freeing function symbols. These issues appear to be fixed in new versions of mCRL2, but the fixes are not straightforwardly backported to the revision we use here. (r11703)

I suggest you either try with an older compiler, if you want to use the exact versions that were used to generate the linked parity games, or use the generated parity games that are linked to from the README. In the meantime I will try to update the toolchain such that it uses the recent mCRL2 release (201707.1) to generate the games.

[mcrl2-r11703-build-ubuntu.patch.zip](https://github.com/jkeiren/paritygame-generator/files/1179330/mcrl2-r11703-build-ubuntu.patch.zip)

**Comment by jkeiren** [comment]
Given that the previous version of mCRL2 did not work with new compilers on, e.g., Ubuntu, I have updated master to use the 201707.1 release of mCRL2 in commit a50925d. Note that I have not checked whether the generated parity games are identical to the ones that were generated using r11703 of mCRL2, so if you want to compare results with results from the literature, you might want to consider using the generated parity games.
